version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - spring-mongo-net

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_app
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/mongo_db
    networks:
      - spring-mongo-net

volumes:
  mongo_data:

networks:
  spring-mongo-net:
    driver: bridge
